FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
WORKDIR /app
COPY ../ .
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --no-lockfile
EXPOSE 3030
CMD [ "pnpm", "start" ]
